### ISSUE TITLE
Pypi package does not contain license

### ISSUE THREAD

**Issue by scarabeusiv** [ur1katz/casttube#3]
Could you please ship license file on the released archive that is found on pypi? Usually just adding/tweaking MANIFEST.in is enough.

**Comment by ur1katz** [comment]
I'm planing a new release in the next few weeks so i'll add the licence to that. The licence is defined "MIT" in the setup.py it just doesn't contain the full licence file. 
If you need it before the next release contact me directly via email.

**Comment by ur1katz** [comment]
Better late than never. License file is included in release 0.2.1
