### ISSUE TITLE
Fetch all queued video ids from cc

### ISSUE THREAD

**Issue by theychx** [ur1katz/casttube#4]
Howdy
The android yt-app has the ability to sync current playlist with whatever is queued on a chromecast. Which means that it should be possible for ```casttube``` to fetch playlist data from the cc as well.
This data would give us all sorts of possibilities with regards to playlist manipulation and navigation in [catt](https://github.com/skorokithakis/catt).

**Comment by ur1katz** [comment]
Hey,
Do you need the playlist data or just to join a playing playlist? 
I think just calling _start_session() should work for joining a current playlist. this gives you the now playing video id and the playlist id.
If you need the data of all of the videos ill need to figure out how they did it in the app(it would probably take me a few weeks to find some time to do it..)

**Comment by theychx** [comment]
Yep, I need the data of all of the videos. And I'm not in a hurry, so don't stress. :smiley:

**Comment by ur1katz** [comment]
Hi, 
I finally made some progress with this issue. I found a request used in the old api that gives me some info about videos in the queue.
feature_queue_data branch currently has the option to return the index, videos id of all videos in the queue. It should also be possible to get the video title and description if that helps. 
I also added a get_session_data that returns some info about the session and the currently playing video

**Comment by theychx** [comment]
Fantastic news! :champagne: 
> It should also be possible to get the video title and description if that helps

That would be super-useful.

**Comment by ur1katz** [comment]
@theychx  Iv'e had some inconsistencies with #9 Could you have a look and tell me what you think?

**Comment by ur1katz** [comment]
Added to release 0.2.1
